"""users table

Revision ID: b5444678a4b1
Revises: 6adcfd62c004
Create Date: 2020-06-28 04:43:00.224101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5444678a4b1'
down_revision = '6adcfd62c004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.drop_column('car', 'user_id')
    op.add_column('user', sa.Column('car_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'car', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'car_id')
    op.add_column('car', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'car', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
